### ISSUE TITLE
Presentation slides and landing page footer

### ISSUE THREAD

**Issue by Agbani123** [zuri-training/Team_37_my_debtors#1]

**Comment by Frankoboss** [comment]
[https://github.com/zuri-training/Team_37_my_debtors/tree/static/frontend/Footer%20for%20landing%20page](url)

**Comment by Frankoboss** [comment]
I wrote the code for the footer of our landing page

**Comment by Frankoboss** [comment]
[https://github.com/zuri-training/Team_37_my_debtors/tree/static/frontend/Guardian%20Signup%20Page](url)

**Comment by Frankoboss** [comment]
I made our initial Guardian Signup page

**Comment by Frankoboss** [comment]
[https://github.com/zuri-training/Team_37_my_debtors/tree/static/frontend/Updated%20Guardian%20Signup%20Page](url)

**Comment by Frankoboss** [comment]
Then when changes were made i updated the Guardian signup page

**Comment by Frankoboss** [comment]
> https://docs.google.com/presentation/d/1Z_81yHxwntE4N5a73mH66A2xuq9jrwa_uLl8GLNBn2A/edit?usp=sharing

**Comment by Frankoboss** [comment]
I made the slides for our first presentation
